apiVersion: v1
kind: Service
metadata:
  labels:
    ppa: productpage
    service: productpage
  name: productpage
  namespace: book1
spec:
  clusterIP: 172.30.123.170
  clusterIPs:
  - 172.30.123.170
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    ppa: productpage
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
