apiVersion: v1
kind: Service
metadata:
  labels:
    ppa: reviews
    service: reviews
  name: reviews
  namespace: book1
spec:
  clusterIP: 172.30.189.149
  clusterIPs:
  - 172.30.189.149
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    ppa: reviews
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
